---
## ---------------------------------------------------------------------------------------------------------------------
driver:
## ---------------------------------------------------------------------------------------------------------------------
  name: vagrant

## ---------------------------------------------------------------------------------------------------------------------
provisioner:
## ---------------------------------------------------------------------------------------------------------------------
  name: chef_solo
  
## ---------------------------------------------------------------------------------------------------------------------
platforms:
## ---------------------------------------------------------------------------------------------------------------------
  - name: centos-5.11

## ---------------------------------------------------------------------------------------------------------------------
suites:
## ---------------------------------------------------------------------------------------------------------------------
