Metrics/LineLength:
  Max: 120
Layout/CaseIndentation:
  IndentOneStep: true
Style/Documentation:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/Next:
  Enabled: false
Style/ParenthesesAroundCondition:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
Style/WordArray:
  MinSize: 8

## What is this, python?  Right, let's
## skip whitespace-based cops then.
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLines:
  Enabled: false
Layout/EmptyLineBetweenDefs:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false
Layout/SpaceInsideParens:
  Enabled: false
Layout/TrailingBlankLines:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
